### ISSUE TITLE
black screen on ios

### ISSUE THREAD

**Issue by mechpil0t** [UnityLabs/barracuda-style-transfer#2]
screen goes black on play when the target is set to ios (on device and editor)

have tested and the issue does not happen on windows or android

2019.4.14
graphics api set to metal

testing on iphone 11 pro

**Comment by FlorentGuinier** [comment]
Hi @FriskyBishop ,

Regarding, iOS, this demo is meant to be desktop-only.
see https://github.com/Unity-Technologies/barracuda-release/issues/115

I will make this more clear in the repo, thanks for reporting!
