### ISSUE TITLE
does not work with HDRP - no error messages

### ISSUE THREAD

**Issue by mechpil0t** [UnityLabs/barracuda-style-transfer#3]
as the title states, when using HDRP the style transfer does nothing

**Comment by FlorentGuinier** [comment]
Supporting HDRP is not in the scope of this repo/code sample, for simplicity it it is using the builtin renderpipeline.
Please note that the Book of the dead style transfer demo from the blog post is actually using HDRP with style transfer as a postprocess. 

The docs for HDRP postprocessing are thus a good starting point https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@6.9/manual/Post-Processing-Main.html
