### ISSUE TITLE
Not working on HDRP

### ISSUE THREAD

**Issue by jorgeavila** [UnityLabs/barracuda-style-transfer#4]
Hi, i been trying to make it work using HDRP enviroment.
Still can't figurate out how to make it work, or if is possible?

**Comment by FlorentGuinier** [comment]
Hi, For simplicity this repo use the builtin renderpipeline. However please note that the Book of the dead style transfer demo from the blog post is actually using HDRP with style transfer as a postprocess.

The docs for HDRP postprocessing are thus a good starting point https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@6.9/manual/Post-Processing-Main.html :)

**Comment by jorgeavila** [comment]
Yeah, that's what i thought, the resolution is high! Glad to know it can be used using HDRP.
 I'm new using HDRP i will read the documentation and is there a possibility you can share the project?
This is my email jorgeavav@gmail.com

**Comment by FlorentGuinier** [comment]
Unfortunatly the Book of the dead demo is based on partially unreleased asset, so we can't share it atm, also HDRP have evolved quite a bit since then so there is probably a better solution now, however in short that is what we did:
- Added a camera itself using a rendertarget to the scene
- Added a callback after all camera are submitted on HDRP
- When the callback is called applyed style transfer to the rendertarget and blit
Hope it helps!

**Comment by jorgeavila** [comment]
Hi!
Thanks for your help!
In my guess i have to modify BarracudaStyleTransfer.cs here to set style transfer to a render target and here HDAdditionalCameraData.cs add the callback for the style transfer before HDRP is called, i'm right? But i still getting a black screen, if there a possibility that you can share the scripts an look what i'm missing or what i'm doing wrong?

Thanks!

**Comment by FlorentGuinier** [comment]
Hi Jorge, 
What we did is to add a new camera that will apply the style transfer on top of regular HDRP rendering.

Code wise in 
`public class HDRenderPipeline : RenderPipeline`
add an event
`public static event Action<Camera> OnAfterCameraSubmit;`
then in 
`public override void Render(ScriptableRenderContext renderContext, Camera[] cameras)`
after all the camera are rendered add 
```
if(OnAfterCameraSubmit != null)
    OnAfterCameraSubmit(camera);
```
Finally in **BarracudaStyleTransfer.cs**
  ```
void OnAfterCameraSubmit(Camera camera)
{
    if (camera.GetComponent<BarracudaStyleTransfer>() == null)
    {
        //scene camera
        RenderStyleTransfer();
    }
    else
    {
        //final blit to screen
        Graphics.Blit(renderTarget, null as RenderTexture);
    }
}
```
Hope it helps.

Merry christmas to you and all your close ones!

**Comment by jorgeavila** [comment]
Hey! thanks.

Merry christmas to you and your close ones too!
And hopefully a better new year!
