### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rygo6** [UnityLabs/barracuda-style-transfer#5]
Curious, what is the license of this project? Could I use things from it in my unity project?

**Comment by FlorentGuinier** [comment]
Thanks for the question the licence was indeed missing, this as been added: 
https://github.com/UnityLabs/barracuda-style-transfer/commit/48bb5a1adf00cccfd30c03b805254df3c117d315
https://unity3d.com/legal/licenses/Unity_Companion_License

So short answer is yes you can use it (this is the same licence used by SRP for example) :)
