### ISSUE TITLE
how to make it work on URP

### ISSUE THREAD

**Issue by FrauSong** [UnityLabs/barracuda-style-transfer#6]
Hi,

I am trying to only transfer parts of objects in the scene (by using overlapping cameras) and want to convert the pipeline from build-in RP to URP. I am a beginner and really not familar with Unity :cry:. If you could give some hints on how to do this, I will be very grateful. 
Thanks in advance!

**Comment by FlorentGuinier** [comment]
Hi FrauSong,

Unfortunatly at the moment we don't have plan to update this repo to URP or HDRP. We would definitively love to but we rather prioritize the developpement of Barracuda itself at the moment.

Also at the moment URP does not support custom post effect, witch might make the integration more tricky. An option meantime could be integrate this effect using an additional camera a bit like what was proposed [here](https://github.com/UnityLabs/barracuda-style-transfer/issues/4) for HDRP.

Have a great day.
Florent
